const products = [
    {
        id: 1,
        name: 'Phân bón hữu cơ',
        image: 'https://picsum.photos/201',
        description: 'Phân bón hữu cơ chất lượng cao, giúp cải thiện đất và tăng năng suất cây trồng.',
        price: 150000,
        rating: 4.5,
        discount: 10,
        badge: 'Bán chạy',
    },
    {
        id: 2,
        name: 'Hạt giống rau sạch',
        image: 'https://picsum.photos/202',
        description: 'Hạt giống rau sạch, an toàn cho sức khỏe, phù hợp với mọi loại đất.',
        price: 20000,
        rating: 4.8,
        discount: 5,
        badge: 'Mới',
    },
    {
        id: 3,
        name: 'Thuốc trừ sâu sinh học',
        image: 'https://picsum.photos/203',
        description: 'Thuốc trừ sâu sinh học, an toàn cho người sử dụng và môi trường.',
        price: 75000,
        rating: 4.2,
        discount: 15,
        badge: 'Khuyến mãi',
    },
    {
        id: 4,
        name: 'Máy cày mini',
        image: 'https://picsum.photos',
        description: 'Máy cày mini tiện lợi, giúp làm đất nhanh chóng và hiệu quả.',
        price: 2500000,
        rating: 4.7,
        discount: 20,
        badge: 'Hot',
    },
    {
        id: 5,
        name: 'Phân bón lá',
        image: 'https://picsum.photos/205',
        description: 'Phân bón lá cung cấp dinh dưỡng trực tiếp cho cây trồng, giúp tăng trưởng nhanh.',
        price: 120000,
        rating: 4.6,
        discount: 10,
        badge: 'Ưu đãi',
    },
    {
        id: 6,
        name: 'Hạt giống hoa',
        image: 'https://picsum.photos/206',
        description: 'Hạt giống hoa đa dạng, giúp làm đẹp không gian sống của bạn.',
        price: 30000,
        rating: 4.9,
        discount: 5,
        badge: 'Yêu thích',
    },
    {
        id: 7,
        name: 'Phân bón NPK',
        image: 'https://picsum.photos/207',
        description: 'Phân bón NPK cân đối, cung cấp đầy đủ dinh dưỡng cho cây trồng.',
        price: 180000,
        rating: 4.4,
        discount: 10,
        badge: 'Tiết kiệm',
    },
    {
        id: 8,
        name: 'Máy phun thuốc',
        image: 'https://picsum.photos/208',
        description: 'Máy phun thuốc hiệu quả, giúp bảo vệ cây trồng khỏi sâu bệnh.',
        price: 1500000,
        rating: 4.3,
        discount: 15,
        badge: 'Mới ra mắt',
    }
];

export default products;