export const products = [
    {
        id: 1,
        name: 'Phân bón hữu cơ',
        image: 'https://picsum.photos/201',
        description: 'Phân bón hữu cơ chất lượng cao, giúp cải thiện đất và tăng năng suất cây trồng.',
        price: 150000,
        rating: 4.5,
        originalPrice: 160000,
        badge: 'Bán chạy',
    },
    {
        id: 2,
        name: 'Hạt giống rau sạch',
        image: 'https://picsum.photos/202',
        description: 'Hạt giống rau sạch, an toàn cho sức khỏe, phù hợp với mọi loại đất.',
        price: 20000,
        rating: 4.8,
        originalPrice: 50000,
        badge: 'Mới',
    },
    {
        id: 3,
        name: 'Thuốc trừ sâu sinh học',
        image: 'https://picsum.photos/203',
        description: 'Thuốc trừ sâu sinh học, an toàn cho người sử dụng và môi trường.',
        price: 75000,
        rating: 4.2,
        originalPrice: 150000,
        badge: 'Khuyến mãi',
    },
    {
        id: 4,
        name: 'Máy cày mini',
        image: 'https://picsum.photos/204',
        description: 'Máy cày mini tiện lợi, giúp làm đất nhanh chóng và hiệu quả.',
        price: 2500000,
        rating: 4.7,
        originalPrice: 2600000,
        badge: 'Hot',
    },
    {
        id: 5,
        name: 'Phân bón lá',
        image: 'https://picsum.photos/205',
        description: 'Phân bón lá cung cấp dinh dưỡng trực tiếp cho cây trồng, giúp tăng trưởng nhanh.',
        price: 120000,
        rating: 4.6,
        originalPrice: 130000,
        badge: 'Ưu đãi',
    },
    {
        id: 6,
        name: 'Hạt giống hoa',
        image: 'https://picsum.photos/206',
        description: 'Hạt giống hoa đa dạng, giúp làm đẹp không gian sống của bạn.',
        price: 30000,
        rating: 4.9,
        originalPrice: 50000,
        badge: 'Yêu thích',
    },
    {
        id: 7,
        name: 'Phân bón NPK 16-16-8 (Bao 50kg) - Cung cấp dinh dưỡng cân đối',
        image: 'https://picsum.photos/207',
        description: 'Phân bón NPK cân đối, cung cấp đầy đủ dinh dưỡng cho cây trồng.',
        price: 180000,
        rating: 4.4,
        originalPrice: 190000,
        badge: 'Tiết kiệm',
    },
    {
        id: 8,
        name: 'Máy phun thuốc',
        image: 'https://picsum.photos/208',
        description: 'Máy phun thuốc hiệu quả, giúp bảo vệ cây trồng khỏi sâu bệnh.',
        price: 1500000,
        rating: 4.3,
        originalPrice: 1600000,
        badge: 'Mới ra mắt',
    },
    {
        id: 9,
        name: 'Phân bón hữu cơ vi sinh',
        image: 'https://picsum.photos/209',
        description: 'Phân bón hữu cơ vi sinh, giúp cải thiện chất lượng đất và tăng cường sức khỏe cây trồng.',
        price: 160000,
        rating: 4.5,
        originalPrice: 170000,
        badge: 'Bán chạy',
    },
    {
        id: 10,
        name: 'Hạt giống cây ăn quả',
        image: 'https://picsum.photos/210',
        description: 'Hạt giống cây ăn quả chất lượng cao, cho trái ngọt và năng suất cao.',
        price: 25000,
        rating: 4.8,
        originalPrice: 30000,
        badge: 'Mới',
    },
    {
        id: 11,
        name: 'Thuốc trừ bệnh cây trồng',
        image: 'https://picsum.photos/211',
        description: 'Thuốc trừ bệnh cây trồng hiệu quả, an toàn cho sức khỏe người sử dụng.',
        price: 80000,
        rating: 4.2,
        originalPrice: 150000,
        badge: 'Khuyến mãi',
    },
    {
        id: 12,
        name: 'Máy xới đất',
        image: 'https://picsum.photos/212',
        description: 'Máy xới đất mạnh mẽ, giúp làm đất nhanh chóng và hiệu quả.',
        price: 3000000,
        rating: 4.7,
        originalPrice: 3200000,
        badge: 'Hot',
    },
    {
        id: 13,
        name: 'Phân bón hữu cơ sinh học',
        image: 'https://picsum.photos/213',
        description: 'Phân bón hữu cơ sinh học, cung cấp dinh dưỡng tự nhiên cho cây trồng.',
        price: 140000,
        rating: 4.6,
        originalPrice: 150000,
        badge: 'Ưu đãi',
    },
    {
        id: 14,
        name: 'Hạt giống rau củ',
        image: 'https://picsum.photos/214',
        description: 'Hạt giống rau củ đa dạng, an toàn cho sức khỏe và dễ trồng.',
        price: 35000,
        rating: 4.9,
        originalPrice: 50000,
        badge: 'Yêu thích',
    },
    {
        id: 15,
        name: 'Phân bón lá hữu cơ',
        image: 'https://picsum.photos/215',
        description: 'Phân bón lá hữu cơ, giúp cây trồng phát triển mạnh mẽ và khỏe mạnh.',
        price: 130000,
        rating: 4.4,
        originalPrice: 140000,
        badge: 'Tiết kiệm',
    },
];

export const productsData = [
    {
        id: 1,
        name: "Phân bón NPK 16-16-8 (Bao 50kg)",
        price: 450000,
        originalPrice: 500000,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.8,
        reviews: 124,
        badge: "Bán chạy",
        category: "phan-bon",
        description:
            "Phân bón NPK 16-16-8 là loại phân bón tổng hợp cân bằng, chứa đầy đủ các chất dinh dưỡng cần thiết cho cây trồng. Sản phẩm được sản xuất theo công nghệ hiện đại, đảm bảo chất lượng và hiệu quả cao.",
        specifications: {
            "Thành phần": "N: 16%, P2O5: 16%, K2O: 8%",
            "Trọng lượng": "50kg/bao",
            "Xuất xứ": "Việt Nam",
            "Hạn sử dụng": "3 năm kể từ ngày sản xuất",
            "Bảo quản": "Nơi khô ráo, thoáng mát",
        },
        usage:
            "Phù hợp cho tất cả các loại cây trồng như lúa, ngô, rau màu, cây ăn quả. Sử dụng 2-3 lần trong một vụ, mỗi lần 20-30kg/1000m².",
        brand: "Phú Mỹ",
        sku: "NPK-16168-50KG",
        inStock: true,
        stockQuantity: 150,
        images: [
            "https://picsum.photos/200",
            "https://picsum.photos/201",
            "https://picsum.photos/202",
            "https://picsum.photos/203",
            "https://picsum.photos/204",
            "https://picsum.photos/205",
            "https://picsum.photos/206",
            "https://picsum.photos/207",
            "https://picsum.photos/208",
            "https://picsum.photos/209",
            "https://picsum.photos/210",
        ],
    },
    {
        id: 2,
        name: "Hạt giống lúa ST25 (1kg)",
        price: 85000,
        originalPrice: 95000,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.9,
        reviews: 89,
        badge: "Mới",
        category: "hat-giong",
        description:
            "Giống lúa ST25 là giống lúa đặc sản nổi tiếng của Việt Nam, cho gạo thơm ngon, dẻo. Sản phẩm có khả năng chống chịu sâu bệnh tốt, phù hợp với nhiều vùng đất.",
        specifications: {
            "Loại giống": "Lúa đặc sản",
            "Trọng lượng": "1kg/gói",
            "Xuất xứ": "Việt Nam",
            "Tỷ lệ nảy mầm": ">= 90%",
            "Thời gian sinh trưởng": "95-105 ngày",
        },
        usage: "Gieo sạ hoặc cấy. Lượng giống 100-120kg/ha. Bón phân cân đối theo từng giai đoạn sinh trưởng của cây lúa.",
        brand: "Vinaseed",
        sku: "ST25-1KG",
        inStock: true,
        stockQuantity: 200,
        images: [
            "/placeholder.svg?height=500&width=500&text=ST25 1",
            "/placeholder.svg?height=500&width=500&text=ST25 2",
            "/placeholder.svg?height=500&width=500&text=ST25 3",
        ],
    },
    {
        id: 3,
        name: "Thuốc trừ sâu sinh học BT (500ml)",
        price: 320000,
        originalPrice: null,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.7,
        reviews: 156,
        badge: "Khuyến mãi",
        category: "thuoc-bvtv",
        description:
            "Thuốc trừ sâu sinh học BT (Bacillus thuringiensis) là sản phẩm an toàn, thân thiện với môi trường, chuyên trị các loại sâu ăn lá trên rau màu, cây ăn quả.",
        specifications: {
            "Thành phần chính": "Bacillus thuringiensis",
            "Dung tích": "500ml",
            "Đối tượng": "Sâu tơ, sâu xanh, sâu khoang",
            "Độc tính": "Không độc hại với người và vật nuôi",
            "Hạn sử dụng": "2 năm",
        },
        usage:
            "Pha 20-30ml thuốc với 16-20 lít nước. Phun đều lên cây khi sâu non mới xuất hiện. Phun vào chiều mát hoặc sáng sớm.",
        brand: "BioGreen",
        sku: "BT-500ML",
        inStock: true,
        stockQuantity: 80,
        images: ["/placeholder.svg?height=500&width=500&text=BT 1", "/placeholder.svg?height=500&width=500&text=BT 2"],
    },
    {
        id: 4,
        name: "Máy phun thuốc mini 16L",
        price: 2850000,
        originalPrice: 3200000,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.6,
        reviews: 43,
        badge: "Giảm giá",
        category: "thiet-bi",
        description:
            "Máy phun thuốc mini dung tích 16L, sử dụng pin lithium, thiết kế nhỏ gọn, dễ dàng di chuyển và sử dụng cho các diện tích canh tác nhỏ và vừa.",
        specifications: {
            "Dung tích bình": "16 lít",
            "Loại pin": "Lithium 12V/8Ah",
            "Thời gian sạc": "6-8 giờ",
            "Thời gian sử dụng": "4-6 giờ",
            "Áp lực phun": "0.15-0.4 MPa",
        },
        usage:
            "Sạc đầy pin trước khi sử dụng. Pha thuốc theo tỷ lệ khuyến cáo, đổ vào bình. Đeo máy và phun đều lên cây trồng. Vệ sinh máy sau khi sử dụng.",
        brand: "AgriTech",
        sku: "MP-16L-MINI",
        inStock: true,
        stockQuantity: 30,
        images: [
            "/placeholder.svg?height=500&width=500&text=Máy phun 1",
            "/placeholder.svg?height=500&width=500&text=Máy phun 2",
            "/placeholder.svg?height=500&width=500&text=Máy phun 3",
        ],
    },
    {
        id: 5,
        name: "Phân bón hữu cơ vi sinh (Bao 25kg)",
        price: 220000,
        originalPrice: 250000,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.9,
        reviews: 67,
        badge: "Mới",
        category: "phan-bon",
        description:
            "Phân bón hữu cơ vi sinh được sản xuất từ nguyên liệu tự nhiên, cung cấp dinh dưỡng đầy đủ cho cây trồng, cải tạo đất và bảo vệ môi trường.",
        specifications: {
            "Thành phần": "Hữu cơ, vi sinh vật có lợi",
            "Trọng lượng": "25kg/bao",
            "Xuất xứ": "Việt Nam",
            "Hạn sử dụng": "2 năm kể từ ngày sản xuất",
            "Bảo quản": "Nơi khô ráo, thoáng mát",
        },
        usage:
            "Sử dụng 50-100kg/1000m² tùy theo loại cây trồng. Rải đều lên mặt đất hoặc trộn với đất trước khi gieo trồng.",
        brand: "EcoFarm",
        sku: "HUUCO-VISINH-25KG",
        inStock: true,
        stockQuantity: 120,
        images: [
            "/placeholder.svg?height=500&width=500&text=Phân bón hữu cơ 1",
            "/placeholder.svg?height=500&width=500&text=Phân bón hữu cơ 2",
            "/placeholder.svg?height=500&width=500&text=Phân bón hữu cơ 3",
        ],
    },
    {
        id: 6,
        name: "Hạt giống rau muống (100g)",
        price: 15000,
        originalPrice: 20000,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.5,
        reviews: 110,
        badge: "Bán chạy",
        category: "hat-giong",
        description:
            "Hạt giống rau muống chất lượng cao, tỷ lệ nảy mầm cao, phù hợp với khí hậu Việt Nam, cho năng suất cao.",
        specifications: {
            "Loại giống": "Rau muống nước",
            "Trọng lượng": "100g/gói",
            "Tỷ lệ nảy mầm": ">= 95%",
            "Thời gian sinh trưởng": "30-35 ngày",
            "Xuất xứ": "Việt Nam",
        },
        usage:
            "Gieo hạt trực tiếp xuống đất hoặc trồng trong chậu. Lượng giống 1-2kg/1000m². Tưới nước đều và bón phân định kỳ.",
        brand: "GreenSeed",
        sku: "RAUMUONG-100G",
        inStock: true,
        stockQuantity: 500,
        images: [
            "/placeholder.svg?height=500&width=500&text=Rau muống 1",
            "/placeholder.svg?height=500&width=500&text=Rau muống 2",
            "/placeholder.svg?height=500&width=500&text=Rau muống 3",
        ],
    },
    {
        id: 7,
        name: "Phân bón lá hữu cơ (Chai 500ml)",
        price: 85000,
        originalPrice: 100000,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.6,
        reviews: 75,
        badge: "Ưu đãi",
        category: "phan-bon",
        description:
            "Phân bón lá hữu cơ cung cấp dinh dưỡng trực tiếp cho cây trồng, giúp tăng trưởng nhanh và khỏe mạnh, an toàn cho sức khỏe người tiêu dùng.",
        specifications: {
            "Thành phần": "Hữu cơ, vi lượng",
            "Dung tích": "500ml/chai",
            "Xuất xứ": "Việt Nam",
            "Hạn sử dụng": "1 năm kể từ ngày sản xuất",
            "Bảo quản": "Nơi khô ráo, thoáng mát",
        },
        usage:
            "Pha loãng 10-15ml phân bón với 1 lít nước. Phun đều lên lá cây vào sáng sớm hoặc chiều mát. Sử dụng 2-3 lần trong một tháng.",
        brand: "OrganicFarm",
        sku: "PHANBONLA-HUUCO-500ML",
        inStock: true,
        stockQuantity: 300,
        images: [
            "/placeholder.svg?height=500&width=500&text=Phân bón lá hữu cơ 1",
            "/placeholder.svg?height=500&width=500&text=Phân bón lá hữu cơ 2",
            "/placeholder.svg?height=500&width=500&text=Phân bón lá hữu cơ 3",
        ],
    },
    {
        id: 8,
        name: "Máy cày đất đa năng (Model X1)",
        price: 4500000,
        originalPrice: 5000000,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.8,
        reviews: 60,
        badge: "Hot",
        category: "thiet-bi",
        description:
            "Máy cày đất đa năng Model X1, công suất mạnh mẽ, thiết kế nhỏ gọn, dễ dàng sử dụng cho các diện tích canh tác nhỏ và vừa.",
        specifications: {
            "Công suất": "3.5HP",
            "Trọng lượng": "50kg",
            "Kích thước": "1200 x 600 x 800 mm",
            "Bảo hành": "12 tháng",
            "Xuất xứ": "Việt Nam",
        },
        usage:
            "Sử dụng để cày xới đất, làm đất trước khi gieo trồng. Đảm bảo an toàn khi vận hành và bảo trì máy định kỳ.",
        brand: "AgriTech",
        sku: "MAYCAY-X1",
        inStock: true,
        stockQuantity: 20,
        images: [
            "/placeholder.svg?height=500&width=500&text=Mô hình X1 1",
            "/placeholder.svg?height=500&width=500&text=Mô hình X1 2",
            "/placeholder.svg?height=500&width=500&text=Mô hình X1 3",
        ],
    },
    {
        id: 9,
        name: "Máy phun thuốc trừ sâu (Model P1)",
        price: 1500000,
        originalPrice: 1800000,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.7,
        reviews: 40,
        badge: "Bán chạy",
        category: "thiet-bi",
        description:
            "Máy phun thuốc trừ sâu Model P1, thiết kế nhỏ gọn, dễ dàng sử dụng, giúp phun thuốc hiệu quả cho cây trồng.",
        specifications: {
            "Công suất": "1.5HP",
            "Dung tích bình chứa": "16L",
            "Trọng lượng": "10kg",
            "Xuất xứ": "Việt Nam",
        },
        usage:
            "Sử dụng để phun thuốc trừ sâu cho cây trồng. Đảm bảo an toàn khi vận hành và bảo trì máy định kỳ.",
        brand: "AgriTech",
        sku: "MAPHUN-P1",
        inStock: true,
        stockQuantity: 50,
        images: [
            "/placeholder.svg?height=500&width=500&text=Mô hình P1 1",
            "/placeholder.svg?height=500&width=500&text=Mô hình P1 2",
            "/placeholder.svg?height=500&width=500&text=Mô hình P1 3",
        ],
    },
    {
        id: 10,
        name: "Phân bón hữu cơ sinh học (Bao 20kg)",
        price: 180000,
        originalPrice: 200000,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.5,
        reviews: 90,
        badge: "Ưu đãi",
        category: "phan-bon",
        description:
            "Phân bón hữu cơ sinh học cung cấp dinh dưỡng tự nhiên cho cây trồng, giúp cải tạo đất và bảo vệ môi trường.",
        specifications: {
            "Thành phần": "Hữu cơ, vi sinh vật có lợi",
            "Trọng lượng": "20kg/bao",
            "Xuất xứ": "Việt Nam",
            "Hạn sử dụng": "2 năm kể từ ngày sản xuất",
            "Bảo quản": "Nơi khô ráo, thoáng mát",
        },
        usage:
            "Sử dụng 40-80kg/1000m² tùy theo loại cây trồng. Rải đều lên mặt đất hoặc trộn với đất trước khi gieo trồng.",
        brand: "EcoFarm",
        sku: "HUUCO-SINHOC-20KG",
        inStock: true,
        stockQuantity: 100,
        images: [
            "/placeholder.svg?height=500&width=500&text=Phân bón hữu cơ sinh học 1",
            "/placeholder.svg?height=500&width=500&text=Phân bón hữu cơ sinh học 2",
            "/placeholder.svg?height=500&width=500&text=Phân bón hữu cơ sinh học 3",
        ],
    },
    {
        id: 11,
        name: "Hạt giống cà chua bi (50g)",
        price: 30000,
        originalPrice: 40000,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.8,
        reviews: 55,
        badge: "Mới",
        category: "hat-giong",
        description:
            "Hạt giống cà chua bi chất lượng cao, tỷ lệ nảy mầm cao, cho quả ngọt và năng suất cao.",
        specifications: {
            "Loại giống": "Cà chua bi",
            "Trọng lượng": "50g/gói",
            "Tỷ lệ nảy mầm": ">= 90%",
            "Thời gian sinh trưởng": "60-70 ngày",
            "Xuất xứ": "Việt Nam",
        },
        usage:
            "Gieo hạt trực tiếp xuống đất hoặc trồng trong chậu. Lượng giống 1-2kg/1000m². Tưới nước đều và bón phân định kỳ.",
        brand: "GreenSeed",
        sku: "CACHUA-BI-50G",
        inStock: true,
        stockQuantity: 400,
        images: [
            "/placeholder.svg?height=500&width=500&text=Cà chua bi 1",
            "/placeholder.svg?height=500&width=500&text=Cà chua bi 2",
            "/placeholder.svg?height=500&width=500&text=Cà chua bi 3",
        ],
    },
    {
        id: 12,
        name: "Phân bón lá sinh học (Chai 1L)",
        price: 120000,
        originalPrice: 150000,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.6,
        reviews: 80,
        badge: "Giảm giá",
        category: "phan-bon",
        description:
            "Phân bón lá sinh học cung cấp dinh dưỡng trực tiếp cho cây trồng, giúp tăng trưởng nhanh và khỏe mạnh, an toàn cho sức khỏe người tiêu dùng.",
        specifications: {
            "Thành phần": "Hữu cơ, vi lượng",
            "Dung tích": "1L/chai",
            "Xuất xứ": "Việt Nam",
            "Hạn sử dụng": "1 năm kể từ ngày sản xuất",
            "Bảo quản": "Nơi khô ráo, thoáng mát",
        },
        usage:
            "Pha loãng 20-30ml phân bón với 1 lít nước. Phun đều lên lá cây vào sáng sớm hoặc chiều mát. Sử dụng 2-3 lần trong một tháng.",
        brand: "OrganicFarm",
        sku: "PHANBONLA-SINHOC-1L",
        inStock: true,
        stockQuantity: 250,
        images: [
            "/placeholder.svg?height=500&width=500&text=Phân bón lá sinh học 1",
            "/placeholder.svg?height=500&width=500&text=Phân bón lá sinh học 2",
            "/placeholder.svg?height=500&width=500&text=Phân bón lá sinh học 3",
        ],
    },
    {
        id: 13,
        name: "Máy xới đất mini (Model X2)",
        price: 3500000,
        originalPrice: 4000000,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.7,
        reviews: 30,
        badge: "Bán chạy",
        category: "thiet-bi",
        description:
            "Máy xới đất mini Model X2, công suất mạnh mẽ, thiết kế nhỏ gọn, dễ dàng sử dụng cho các diện tích canh tác nhỏ và vừa.",
        specifications: {
            "Công suất": "3HP",
            "Trọng lượng": "45kg",
            "Kích thước": "1100 x 550 x 750 mm",
            "Bảo hành": "12 tháng",
            "Xuất xứ": "Việt Nam",
        },
        usage:
            "Sử dụng để xới đất, làm đất trước khi gieo trồng. Đảm bảo an toàn khi vận hành và bảo trì máy định kỳ.",
        brand: "AgriTech",
        sku: "MAYXO-X2",
        inStock: true,
        stockQuantity: 15,
        images: [
            "/placeholder.svg?height=500&width=500&text=Mô hình X2 1",
            "/placeholder.svg?height=500&width=500&text=Mô hình X2 2",
            "/placeholder.svg?height=500&width=500&text=Mô hình X2 3",
        ],
    },
    {
        id: 14,
        name: "Hạt giống bắp ngọt (200g)",
        price: 40000,
        originalPrice: 50000,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.8,
        reviews: 65,
        badge: "Mới",
        category: "hat-giong",
        description:
            "Hạt giống bắp ngọt chất lượng cao, tỷ lệ nảy mầm cao, cho quả ngọt và năng suất cao.",
        specifications: {
            "Loại giống": "Bắp ngọt",
            "Trọng lượng": "200g/gói",
            "Tỷ lệ nảy mầm": ">= 90%",
            "Thời gian sinh trưởng": "70-80 ngày",
            "Xuất xứ": "Việt Nam",
        },
        usage:
            "Gieo hạt trực tiếp xuống đất hoặc trồng trong chậu. Lượng giống 1-2kg/1000m². Tưới nước đều và bón phân định kỳ.",
        brand: "GreenSeed",
        sku: "BAPNGOT-200G",
        inStock: true,
        stockQuantity: 300,
        images: [
            "/placeholder.svg?height=500&width=500&text=Bắp ngọt 1",
            "/placeholder.svg?height=500&width=500&text=Bắp ngọt 2",
            "/placeholder.svg?height=500&width=500&text=Bắp ngọt 3",
        ],
    },
    {
        id: 15,
        name: "Phân bón hữu cơ vi sinh (Bao 50kg)",
        price: 400000,
        originalPrice: 450000,
        image: "/placeholder.svg?height=300&width=300",
        rating: 4.9,
        reviews: 50,
        badge: "Ưu đãi",
        category: "phan-bon",
        description:
            "Phân bón hữu cơ vi sinh được sản xuất từ nguyên liệu tự nhiên, cung cấp dinh dưỡng đầy đủ cho cây trồng, cải tạo đất và bảo vệ môi trường.",
        specifications: {
            "Thành phần": "Hữu cơ, vi sinh vật có lợi",
            "Trọng lượng": "50kg/bao",
            "Xuất xứ": "Việt Nam",
            "Hạn sử dụng": "2 năm kể từ ngày sản xuất",
            "Bảo quản": "Nơi khô ráo, thoáng mát",
        },
        usage:
            "Sử dụng 100-200kg/1000m² tùy theo loại cây trồng. Rải đều lên mặt đất hoặc trộn với đất trước khi gieo trồng.",
        brand: "EcoFarm",
        sku: "HUUCO-VISINH-50KG",
        inStock: true,
        stockQuantity: 80,
        images: [
            "/placeholder.svg?height=500&width=500&text=Phân bón hữu cơ vi sinh 1",
            "/placeholder.svg?height=500&width=500&text=Phân bón hữu cơ vi sinh 2",
            "/placeholder.svg?height=500&width=500&text=Phân bón hữu cơ vi sinh 3",
        ],
    }
]
